local theme = require("theme")

describe("theme.border", function()
  it("maps mode colors to Catppuccin Frappe argb", function()
    assert.are.equal("0xffca9ee6", theme.border.active)
    assert.are.equal("0xff51576d", theme.border.inactive)
    assert.are.equal("0xffe78284", theme.border.zoom)
    assert.are.equal("0xffef9f76", theme.border.resize)
    assert.are.equal("0xff8caaee", theme.border.service)
  end)
  it("never reuses red for a mode color", function()
    assert.are_not.equal(theme.border.zoom, theme.border.resize)
    assert.are_not.equal(theme.border.zoom, theme.border.service)
  end)
end)
