#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# General
# add 20 padding to the top and 0 padding to the bottom of every space located on the main display
# yabai -m config external_bar main:0:0
# add 25 padding to the top and bottom of all spaces regardless of the display it belongs to
yabai -m config external_bar all:25:0

yabai -m config window_placement second_child
# yabai -m config window_topmost on
# yabai -m config window_opacity off
# yabai -m config window_opacity_duration 0.0
# yabai -m config window_shadow on
# yabai -m config insert_feedback_color 0xaad75f5f
# yabai -m config active_window_opacity 1.0
# yabai -m config split_ratio 0.50
# yabai -m config normal_window_opacity 0.90
# yabai -m config auto_balance off

# Mouse
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
# yabai -mouse mouse_drop_action swap

# Layout
yabai -m config layout bsp
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# Ignore
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pulse Secure$" manage=off
# Float Windows
yabai -m rule --add app=Finder manage=off
yabai -m rule --add app=Tweetbot manage=off
# yabai -m rule --add app=Photoshop manage=off
# yabai -m rule --add app=Illustrator  manage=off
yabai -m rule --add app=Vox manage=off
yabai -m rule --add app=checkra1n manage=off
yabai -m rule --add app=ColorSlurp manage=off
yabai -m rule --add app=System Preferences manage=off
yabai -m rule --add app=VOX manage=off
yabai -m rule --add app=The\ Unarchiver manage=off
yabai -m rule --add app=System\ Preferences manage=off
yabai -m rule --add app=".*CleanMyMac.*" manage=off
yabai -m rule --add app=".*1Password.*" manage=off
yabai -m rule --add app=Surfshark manage=off
yabai -m rule --add app=Calculator manage=off
yabai -m rule --add app=Kodi manage=off
yabai -m rule --add app=VLC manage=off
yabai -m rule --add app="Axis & Allies 1942 Online" manage=off
yabai -m rule --add app="AxisAndAllies1942Online" manage=off
yabai -m rule --add app="Alfred Preferences" manage=off

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# To fix when using synergy
# ref https://github.com/koekeishiya/yabai/issues/719#issuecomment-2038328430
yabai -m signal --add event=space_changed action='yabai -m window --focus $(yabai -m query --windows --space | jq -r '\''[.[]|select(."is-visible")][0].id'\'')'

borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

# change borders color when zoom-fullscreen

yabai -m signal --add event=window_focused action="~/.config/jankyborders/maximize-border.sh"
yabai -m signal --add event=window_resized action="~/.config/jankyborders/maximize-border.sh"

# restart sketchybar when display changes
yabai -m signal --add event=display_removed action="sketchybar --reload && external_bar --reload" # this could cost performance
yabai -m signal --add event=display_added action="sketchybar --reload && external_bar --reload" # same here
yabai -m signal --add event=system_woke action="sketchybar --reload && external_bar --reload"
sketchybar --reload && external_bar --reload

brew install yabai --HEAD

echo "Yabai configuration loaded.."
