#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# General
yabai -m config external_bar all:25:0

yabai -m config window_placement second_child

# Mouse
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# Layout
yabai -m config layout bsp
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# Ignore
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pulse Secure$" manage=off
# Float Windows
yabai -m rule --add app=Tweetbot manage=off
yabai -m rule --add app=Vox manage=off
yabai -m rule --add app=checkra1n manage=off
yabai -m rule --add app=ColorSlurp manage=off
yabai -m rule --add app=System Preferences manage=off
yabai -m rule --add app=VOX manage=off
yabai -m rule --add app=The\ Unarchiver manage=off
yabai -m rule --add app=System\ Preferences manage=off
yabai -m rule --add app=".*CleanMyMac.*" manage=off
yabai -m rule --add app=".*1Password.*" manage=off
yabai -m rule --add app=Surfshark manage=off
yabai -m rule --add app=Kodi manage=off
yabai -m rule --add app=VLC manage=off
yabai -m rule --add app="Axis & Allies 1942 Online" manage=off
yabai -m rule --add app="AxisAndAllies1942Online" manage=off
yabai -m rule --add app="Alfred Preferences" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# To fix when using synergy
# ref https://github.com/koekeishiya/yabai/issues/719#issuecomment-2038328430
yabai -m signal --add event=space_changed action='yabai -m window --focus $(yabai -m query --windows --space | jq -r '\''[.[]|select(."is-visible")][0].id'\'')'

borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

# change borders color when zoom-fullscreen

yabai -m signal --add event=window_focused action="~/.config/jankyborders/maximize-border.sh"
yabai -m signal --add event=window_resized action="~/.config/jankyborders/maximize-border.sh"

yabai -m signal --add event=window_destroyed action="~/.config/skhd/focus-window-on-destroy.sh"

# restart sketchybar when display changes
yabai -m signal --add event=display_removed action="sketchybar --reload && external_bar --reload" # this could cost performance
yabai -m signal --add event=display_added action="sketchybar --reload && external_bar --reload" # same here
yabai -m signal --add event=system_woke action="sketchybar --reload && external_bar --reload"
sketchybar --reload && external_bar --reload

echo "Yabai configuration loaded.."
