#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# General
# yabai -m config external_bar                 all:24:0
yabai -m config window_placement second_child
# yabai -m config window_topmost on
# yabai -m config window_opacity off
# yabai -m config window_opacity_duration 0.0
# yabai -m config window_shadow on
# yabai -m config insert_feedback_color 0xaad75f5f
# yabai -m config active_window_opacity 1.0
# yabai -m config split_ratio 0.50
# yabai -m config normal_window_opacity 0.90
# yabai -m config auto_balance off

# Mouse
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
# yabai -mouse mouse_drop_action swap

# Layout
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 10

# Ignore
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pulse Secure$" manage=off

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# To fix when using synergy
# ref https://github.com/koekeishiya/yabai/issues/719#issuecomment-2038328430
yabai -m signal --add event=space_changed action='yabai -m window --focus $(yabai -m query --windows --space | jq -r '\''[.[]|select(."is-visible")][0].id'\'')'

borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
brew install yabai --HEAD
echo "Yabai configuration loaded.."
