print("Loading vscode_keymaps.lua")
local map = vim.keymap.set
local vscode = require("vscode")
-- .includes('aipopup.action.modal.generate')
local is_cursor = vscode.eval(
    "var commands = await vscode.commands.getCommands(); return commands.includes('aipopup.action.modal.generate');")
local call = vscode.call
local action = vscode.action

-- lsp
map({ "n" }, "gr", function () action("editor.action.goToReferences") end)

-- Code Actions
map({ "n", "x" }, "<leader>cf", function ()
    action("editor.action.formatDocument")
end, { desc = "Format Document" })
map("n", "<leader>cr", function ()
    action("editor.action.rename")
end, { desc = "Rename Symbol" })

-- Buffers
-- workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup
map("n", "<leader>bb", function () action("workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup") end)
map("n", "<leader>bo", function () action("workbench.action.closeOtherEditors") end)
map("n", "<leader>bd", function () action("workbench.action.closeActiveEditor") end)
map("n", "<leader>bD", function () action("workbench.action.closeEditorsInGroup") end)

-- File Explorer
map("n", "<leader>e", function ()
    -- action("workbench.action.toggleSidebarVisibility")
    action("workbench.view.explorer")
end, { desc = "Toggle Primary Sidebar" })
map("n", "<leader>ub", function ()
    action("workbench.action.toggleSidebarVisibility")
end, { desc = "Toggle Secondary/Auxiliary Sidebar" })
map("n", "<leader>uB", function ()
    action("workbench.action.toggleAuxiliaryBar")
end, { desc = "Toggle Secondary/Auxiliary Sidebar" })

-- Diagnostics Navigation
map("n", "<leader>cd", function ()
    action("workbench.actions.view.problems")
end, { desc = "Show Problems" })

map("n", "]d", function ()
    action("editor.action.marker.next")
end, { desc = "Next Diagnostic" })
map("n", "[d", function ()
    action("editor.action.marker.prev")
end, { desc = "Prev Diagnostic" })
map("n", "]e", function ()
    action("editor.action.marker.next")
end, { desc = "Next Error" })
map("n", "[e", function ()
    action("editor.action.marker.prev")
end, { desc = "Prev Error" })
map("n", "]w", function ()
    action("editor.action.marker.next")
end, { desc = "Next Warning" })
map("n", "[w", function ()
    action("editor.action.marker.prev")
end, { desc = "Prev Warning" })

-- File Operations
map("n", "<leader>ff", function ()
    action("workbench.action.quickOpen")
end, { desc = "Find Files" })
map("n", "<leader>fn", function ()
    action("workbench.action.files.newUntitledFile")
end, { desc = "New File" })

-- Git/GitLens
map("n", "<leader>gg", function ()
    action("workbench.view.scm")
end, { desc = "Git Status" })
map("n", "<leader>gG", function ()
    action("workbench.view.scm")
end, { desc = "Git Status" })
map("n", "<leader>gl", function ()
    action("git.viewHistory")
end, { desc = "Git Log" })
map("n", "<leader>gL", function ()
    action("gitlens.gitCommands.history")
end, { desc = "GitLens Log" })
map("n", "<leader>gb", function ()
    action("gitlens.toggleFileBlame:key")
end, { desc = "Git Blame Line" })
map("n", "<leader>gf", function ()
    action("git.viewFileHistory")
end, { desc = "Git File History" })
map("n", "<leader>gF", function ()
    action("gitlens.showQuickFileHistory")
end, { desc = "GitLens File History" })
map({ "n", "x" }, "<leader>gB", function ()
    action("gitlens.openFileOnRemote")
end, { desc = "Git Browser" })

-- Search
map("x", "<leader>sw", function ()
    action("workbench.action.findInFiles")
end, { desc = "Search Word in Files" })

-- Multi-cursor
map({ "n", "x" }, "<leader>r", function ()
    vscode.with_insert(function ()
        vscode.action("editor.action.refactor")
    end)
end)
-- map({ "n", "x", "i" }, "<C-d>", function()
--   vscode.with_insert(function()
--     vscode.action("editor.action.addSelectionToNextFindMatch")
--   end)
-- end)
map({ "n", "x", "i" }, "<leader>n", function ()
    vscode.with_insert(function ()
        vscode.action("editor.action.addSelectionToNextFindMatch")
    end)
end)

-- map({ "n", "x", "i" }, "<up>", function()
--   vscode.with_insert(function()
--     vscode.action("editor.action.insertCursorAbove")
--   end)
-- end)

-- map({ "n", "x", "i" }, "<down>", function()
--   vscode.with_insert(function()
--     vscode.action("editor.action.insertCursorBelow")
--   end)
-- end)

-- UI Toggles
map("n", "<leader>uw", function ()
    action("editor.action.toggleWordWrap")
end, { desc = "Toggle Word Wrap" })
map("n", "<leader>uz", function ()
    action("workbench.action.toggleZenMode")
end, { desc = "Toggle Zen Mode" })
map("n", "<leader>uZ", function ()
    action("workbench.action.toggleMaximizeEditorGroup")
end, { desc = "Toggle Maximize Editor" })

-- AI
map("n", "<leader>aa", function ()
    call(is_cursor and "aichat.newchataction" or "workbench.action.chat.open")
end, { desc = "Open AI Chat" })
map({ "n", "x" }, "<leader>aq", function ()
    call(is_cursor and "aipopup.action.modal.generate" or "inlineChat.start")
end, { desc = "Open AI Inline Chat" })
map({ "n", "x" }, "<leader>as", function ()
    action("workbench.action.chat.attachSelection")
end, { desc = "Add selection to chat" })
map({ "n", "x" }, "<leader>ab", function ()
    action("workbench.action.chat.attachFile")
end, { desc = "Add file/buffer to chat" })

map({ "n", "x" }, "<leader>wH", function () action("workbench.action.moveActiveEditorGroupLeft") end)
map({ "n", "x" }, "<leader>wJ", function () action("workbench.action.moveActiveEditorGroupDown") end)
map({ "n", "x" }, "<leader>wK", function () action("workbench.action.moveActiveEditorGroupUp") end)
map({ "n", "x" }, "<leader>wL", function () action("workbench.action.moveActiveEditorGroupRight") end)
map("n", "<leader>wx", function () action("workbench.action.moveEditorToNextGroup") end)
map("n", "<leader>wX", function () action("workbench.action.moveEditorToPreviousGroup") end)

map({ "n", "x" }, "<leader>wh", function () action("workbench.action.navigateLeft") end)
map({ "n", "x" }, "<leader>wj", function () action("workbench.action.navigateDown") end)
map({ "n", "x" }, "<leader>wk", function () action("workbench.action.navigateUp") end)
map({ "n", "x" }, "<leader>wl", function () action("workbench.action.navigateRight") end)

map("n", "<leader>wd", function () action("workbench.action.closeEditorsInGroup") end)
map("n", "<leader>wq", function () action("workbench.action.closeEditorsInGroup") end)
map("n", "<leader>wo", function () action("workbench.action.closeEditorsInOtherGroups") end)
map("n", "<leader>wv", function () action("workbench.action.splitEditor") end)
map("n", "<leader>ws", function () action("workbench.action.splitEditorDown") end)
map("n", "<leader>wT", function () action("workbench.action.moveEditorToFirstGroup") end)
map("n", "<leader>ww", function () action("workbench.action.focusNextGroup") end)
map("n", "<leader>wW", function () action("workbench.action.focusPreviousGroup") end)
map("n", "<leader>wm", function () action("workbench.action.maximizeEditorHideSidebar") end)

map("n", "<C-Up>", function () action("workbench.action.decreaseViewHeight") end)
map("n", "<C-Down>", function () action("workbench.action.increaseViewHeight") end)
map("n", "<C-Left>", function () action("workbench.action.decreaseViewWidth") end)
map("n", "<C-Right>", function () action("workbench.action.increaseViewWidth") end)
map("n", "<leader>w=", function () action("workbench.action.evenEditorWidths") end)
